name: Build Test
on:
  push:
    branches:
      - main
env:
  VITE_APP_API_AIC=${{ variables.VITE_APP_API_AIC }}
  VITE_APP_HARVARD_API=${{ variables.VITE_APP_HARVARD_API }}
  VITE_APP_HARVARD_API_KEY=${{ secrets.VITE_APP_HARVARD_API_KEY }}
  VITE_APP_RIJKS_API=${{ variables.VITE_APP_RIJKS_API }}
  VITE_APP_RIJKS_API_KEY=${{ secrets.VITE_APP_RIJKS_API_KEY }}

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20'
          cache: 'npm'
      - name: Build and test
        run: |
          npm ci
          npm run build
      - name: Test
        run: npm test
      - name: Deploy
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
